version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: node-auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5432:5432
